window.Admin={
tabs:[['items','Listed Items'],['categories','Categories'],['types','Types'],['textbar','Text Bar'],['orders','Orders'],['messages','Messages'],['pages','Footer Pages'],['guides','Guide Pages'],['settings','Site Settings']],
async render(tab='items'){
 if(Store.state.profile?.role!=='admin'){Store.view('<div class="alert err">Admin access required.</div>');return}
 Store.view(`<nav class="sub-nav">${this.tabs.map(([k,n])=>`<button class="mini ${k===tab?'active':''}" data-tab="${k}">${n}</button>`).join('')}</nav><div id="admin-body"></div>`);document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>this.render(b.dataset.tab));await this[tab]();
},
async items(){
 const {data,error}=await db.from('products').select('*,categories(name),product_types(name)').order('sort_order');if(error)return this.err(error);
 document.getElementById('admin-body').innerHTML=`<h2>Manage Listed Items (${data.length})</h2><form id="product-form" class="panel"><div class="bilingual"><div class="form-group"><label>Title - English</label><input name="title" required></div><div class="form-group"><label>Title - Arabic</label><input name="title_ar" dir="rtl"></div></div><div class="bilingual"><div class="form-group"><label>Price USD</label><input name="price_usd" type="number" step=".01" min="0" required></div><div class="form-group"><label>Discounted Price USD</label><input name="discounted_price_usd" type="number" step=".01" min="0"></div></div><div class="bilingual"><div class="form-group"><label>Stock Quantity</label><input name="stock_quantity" type="number" min="0" value="0"></div><div class="form-group"><label>Status</label><select name="status"><option value="in_stock">In Stock</option><option value="out_of_stock">Out of Stock</option><option value="coming_soon">Coming Soon</option></select></div></div><div class="form-group"><label>Description - English</label><textarea name="description"></textarea></div><div class="form-group"><label>Description - Arabic</label><textarea name="description_ar" dir="rtl"></textarea></div><div class="bilingual"><div class="form-group"><label>Category</label><select name="category_id"><option value="">None</option>${Store.state.categories.map(x=>`<option value="${x.id}">${Store.esc(x.name)}</option>`).join('')}</select></div><div class="form-group"><label>Type</label><select name="type_id"><option value="">None</option>${Store.state.types.map(x=>`<option value="${x.id}">${Store.esc(x.name)}</option>`).join('')}</select></div></div><div class="form-group"><label>PayPal Link</label><input name="paypal_link" type="url"></div><div class="bilingual"><div class="form-group"><label>Display Order</label><input name="sort_order" type="number" value="999999"></div><div class="form-group"><label><input name="active" type="checkbox" checked style="width:auto"> Active</label></div></div><button class="btn success">Add Listed Item</button></form><div class="table-wrap"><table><thead><tr><th>Title</th><th>Price</th><th>Stock</th><th>Status</th><th>Order</th><th>Action</th></tr></thead><tbody>${data.map(p=>`<tr><td>${Store.esc(p.title)}</td><td>${Number(p.price_usd).toFixed(2)}</td><td>${p.stock_quantity}</td><td>${p.status}</td><td>${p.sort_order}</td><td><button class="btn danger del-product" data-id="${p.id}">Delete</button></td></tr>`).join('')}</tbody></table></div><p class="muted">Image upload, included-content editor, expenses editor and full product editing are the next admin milestone.</p>`;
 document.getElementById('product-form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),o=Object.fromEntries(f);o.price_usd=Number(o.price_usd);o.discounted_price_usd=o.discounted_price_usd?Number(o.discounted_price_usd):null;o.stock_quantity=Number(o.stock_quantity);o.sort_order=Number(o.sort_order);o.active=f.has('active');o.category_id=o.category_id||null;o.type_id=o.type_id||null;let r=await db.from('products').insert(o);if(r.error)return this.err(r.error);await Products.load();Store.alert('Listed item added.');this.items()};
 document.querySelectorAll('.del-product').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this item?'))return;let r=await db.from('products').delete().eq('id',b.dataset.id);if(r.error)return this.err(r.error);await Products.load();this.items()});
},
async simpleTable(table,title,nameKey='name',arKey='name_ar'){
 const {data,error}=await db.from(table).select('*').order('sort_order');if(error)return this.err(error);
 document.getElementById('admin-body').innerHTML=`<h2>Manage ${title} (${data.length})</h2><form id="simple-form" class="panel"><div class="bilingual"><div class="form-group"><label>English</label><input name="${nameKey}" required></div><div class="form-group"><label>Arabic</label><input name="${arKey}" dir="rtl"></div></div><div class="form-group"><label>Display Order</label><input name="sort_order" type="number" value="${data.length+1}"></div><button class="btn success">Add</button></form><div class="table-wrap"><table>${data.map(x=>`<tr><td>${Store.esc(x[nameKey]||'')}</td><td dir="rtl">${Store.esc(x[arKey]||'')}</td><td>${x.sort_order}</td><td><button class="btn danger simple-del" data-id="${x.id}">Delete</button></td></tr>`).join('')}</table></div>`;
 document.getElementById('simple-form').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.sort_order=Number(o.sort_order);let r=await db.from(table).insert(o);if(r.error)return this.err(r.error);await Products.load();this.simpleTable(table,title,nameKey,arKey)};
 document.querySelectorAll('.simple-del').forEach(b=>b.onclick=async()=>{if(!confirm('Delete?'))return;let r=await db.from(table).delete().eq('id',b.dataset.id);if(r.error)return this.err(r.error);await Products.load();this.simpleTable(table,title,nameKey,arKey)});
},
categories(){return this.simpleTable('categories','Categories')},types(){return this.simpleTable('product_types','Types')},
textbar(){return this.simpleTable('text_bar','Text Bar','text','text_ar')},
async orders(){const {data,error}=await db.from('orders').select('*,order_items(*)').order('created_at',{ascending:false});if(error)return this.err(error);document.getElementById('admin-body').innerHTML=`<h2>Manage Orders (${data.length})</h2><div class="table-wrap"><table><tr><th>#</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th></tr>${data.map(o=>`<tr><td>${o.order_number}</td><td>${Store.esc(o.first_name+' '+o.last_name)}<br>${Store.esc(o.email)}</td><td>${Number(o.total_usd).toFixed(2)} USD</td><td>${o.status}</td><td>${new Date(o.created_at).toLocaleString()}</td></tr>`).join('')}</table></div>`},
async messages(){const {data,error}=await db.from('messages').select('*').order('created_at',{ascending:false});if(error)return this.err(error);document.getElementById('admin-body').innerHTML=`<h2>Contact Messages (${data.length})</h2><div class="table-wrap"><table>${data.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString()}</td><td>${Store.esc(m.email||'')}</td><td>${Store.esc(m.type||'')}</td><td>${Store.esc(m.message||'')}</td></tr>`).join('')}</table></div>`},
async pages(){return this.contentTable('pages','Footer Pages')},async guides(){return this.contentTable('guide_pages','Guide Pages')},
async contentTable(table,title){const {data,error}=await db.from(table).select('*');if(error)return this.err(error);document.getElementById('admin-body').innerHTML=`<h2>${title}</h2>${data.map(x=>`<div class="card"><strong>${Store.esc(x.title||x.page_key||x.slug||'Page')}</strong><div class="description">${Store.esc((x.content||'').slice(0,250))}</div></div>`).join('')||'<div class="card">No pages yet.</div>'}<p class="muted">Rich page editing will be enabled in the next admin milestone.</p>`},
async settings(){const {data,error}=await db.from('site_settings').select('*').eq('id',1).single();if(error)return this.err(error);document.getElementById('admin-body').innerHTML=`<h2>Site Settings</h2><form id="settings-form" class="panel"><div class="bilingual"><div class="form-group"><label>Site Name</label><input name="site_name" value="${Store.escAttr(data.site_name||'')}"></div><div class="form-group"><label>Site Name Arabic</label><input name="site_name_ar" dir="rtl" value="${Store.escAttr(data.site_name_ar||'')}"></div></div><div class="form-group"><label>Description</label><input name="site_description" value="${Store.escAttr(data.site_description||'')}"></div><div class="form-group"><label>Description Arabic</label><input name="site_description_ar" dir="rtl" value="${Store.escAttr(data.site_description_ar||'')}"></div><div class="form-group"><label>Theme Color</label><input name="theme_color" type="color" value="${Store.escAttr(data.theme_color||'#0066cc')}"></div><button class="btn success">Save Settings</button></form>`;
 document.getElementById('settings-form').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));let r=await db.from('site_settings').update(o).eq('id',1);if(r.error)return this.err(r.error);await Store.loadSettings();Store.applySettings();Store.alert('Settings saved.')}},
err(e){console.error(e);Store.alert(e.message||String(e),'err')}
};