window.Store={
state:{lang:localStorage.getItem('sf_lang')||'en',theme:localStorage.getItem('sf_theme')||'light',user:null,profile:null,settings:{},products:[],categories:[],types:[],textbar:[],notifications:[]},
esc:s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),escAttr:s=>String(s??'').replace(/["&<>]/g,m=>({'"':'&quot;','&':'&amp;','<':'&lt;','>':'&gt;'}[m])),
view:h=>document.getElementById('view').innerHTML=h,
alert(msg,type='ok'){document.getElementById('alert-host').innerHTML=`<div class="alert ${type}">${this.esc(msg)}</div>`;setTimeout(()=>{document.getElementById('alert-host').innerHTML=''},4500)},
modal(h){document.getElementById('modal-body').innerHTML=h;document.getElementById('modal').classList.remove('hidden')},
async loadSettings(){const {data,error}=await db.from('site_settings').select('*').eq('id',1).single();if(error)throw error;this.state.settings=data||{}},
applySettings(){let s=this.state.settings;document.documentElement.lang=this.state.lang;document.documentElement.dir=this.state.lang==='ar'?'rtl':'ltr';document.body.classList.toggle('dark',this.state.theme==='dark');document.documentElement.style.setProperty('--primary',s.theme_color||'#0066cc');let name=localize(s,'site_name')||'StoreFront',desc=localize(s,'site_description')||'';document.getElementById('site-title').textContent=name;document.getElementById('site-subtitle').textContent=desc;document.getElementById('footer-name').textContent=name;document.title=name;document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===this.state.lang));document.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===this.state.theme));document.querySelectorAll('[data-i18n]').forEach(x=>x.textContent=t(x.dataset.i18n));let social=[];if(s.show_social_icons&&s.instagram_url)social.push(`<a class="btn" target="_blank" rel="noopener" href="${this.escAttr(s.instagram_url)}">Instagram</a>`);if(s.show_social_icons&&s.whatsapp_url)social.push(`<a class="btn" target="_blank" rel="noopener" href="${this.escAttr(s.whatsapp_url)}">WhatsApp</a>`);document.getElementById('social-links').innerHTML=social.join(' ')},
renderNav(){let p=this.state.profile,u=this.state.user,a=[['home',t('home')]];if(u)a.push(['cart',`${t('cart')} (${Cart.count()})`],['orders',t('orders')],['account',`${t('account')} (${this.esc(p?.username||'')})`]);if(p?.role==='admin')a.push(['admin',t('admin')]);if(!u)a.push(['login',t('login')],['register',t('register')]);else a.push(['logout',t('logout')]);document.getElementById('main-nav').innerHTML=a.map(([k,n])=>`<a href="#${k}" data-route="${k}" class="btn ${location.hash.slice(1)===k?'active':''}">${n}</a>`).join('');document.querySelectorAll('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();this.go(x.dataset.route)})},
go(r){if(r==='logout'){Auth.logout().then(()=>{this.go('home');this.refreshShell()});return}location.hash=r;this.route()},
async notifications(){if(!this.state.user){document.getElementById('notify-btn').classList.add('hidden');return}document.getElementById('notify-btn').classList.remove('hidden');const {data}=await db.from('notifications').select('*').eq('user_id',this.state.user.id).order('created_at',{ascending:false}).limit(30);this.state.notifications=data||[];let unread=this.state.notifications.filter(n=>!n.read_at&&!n.is_read).length,b=document.getElementById('notify-badge');b.textContent=unread>99?'99+':unread;b.classList.toggle('hidden',!unread);document.getElementById('notify-list').innerHTML=this.state.notifications.map(n=>`<div class="notify-item ${(!n.read_at&&!n.is_read)?'unread':''}"><strong>${this.esc(localize(n,'title'))}</strong><div>${this.esc(localize(n,'message'))}</div><small class="muted">${new Date(n.created_at).toLocaleString()}</small></div>`).join('')||'<div class="notify-item muted">No notifications yet.</div>'},
async route(){let r=(location.hash||'#home').slice(1);this.renderNav();if(r==='home')return Products.renderHome();if(r==='cart')return Cart.render();if(r==='login')return this.loginView();if(r==='register')return this.registerView();if(r==='account')return this.accountView();if(r==='orders')return this.ordersView();if(r==='admin')return Admin.render();return Products.renderHome()},
loginView(){if(this.state.user)return this.go('account');this.view(`<form id="login-form" class="panel"><h2>${t('login')}</h2><div class="form-group"><label>Email</label><input name="email" type="email" required></div><div class="form-group"><label>Password</label><input name="password" type="password" required></div><button class="btn primary">${t('login')}</button></form>`);document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{await Auth.login(f.get('email'),f.get('password'));await this.refreshShell();this.go('home')}catch(x){this.alert(x.message,'err')}}},
registerView(){this.view(`<form id="reg-form" class="panel"><h2>${t('register')}</h2><div class="bilingual"><div class="form-group"><label>Username</label><input name="username" required></div><div class="form-group"><label>Email</label><input name="email" type="email" required></div></div><div class="bilingual"><div class="form-group"><label>First Name</label><input name="first_name"></div><div class="form-group"><label>Last Name</label><input name="last_name"></div></div><div class="form-group"><label>Password</label><input name="password" type="password" minlength="8" required></div><button class="btn primary">${t('register')}</button></form>`);document.getElementById('reg-form').onsubmit=async e=>{e.preventDefault();try{await Auth.register(new FormData(e.target));this.alert('Registration submitted. Check your email if confirmation is enabled.');this.go('login')}catch(x){this.alert(x.message,'err')}}},
accountView(){if(!this.state.user)return this.go('login');let p=this.state.profile||{};this.view(`<form id="account-form" class="panel"><h2>${t('account')}</h2><div class="bilingual"><div class="form-group"><label>Username</label><input name="username" value="${this.escAttr(p.username||'')}" required></div><div class="form-group"><label>Email</label><input value="${this.escAttr(this.state.user.email||'')}" disabled></div></div><div class="bilingual"><div class="form-group"><label>First Name</label><input name="first_name" value="${this.escAttr(p.first_name||'')}"></div><div class="form-group"><label>Last Name</label><input name="last_name" value="${this.escAttr(p.last_name||'')}"></div></div><div class="form-group"><label>Mobile Number</label><input name="mobile_number" value="${this.escAttr(p.mobile_number||'')}"></div><div class="form-group"><label>Delivery Address</label><textarea name="delivery_address">${this.esc(p.delivery_address||'')}</textarea></div><div class="form-group"><label>New Password (leave blank to keep existing)</label><input name="new_password" type="password"></div><button class="btn primary">Save Changes</button></form>`);document.getElementById('account-form').onsubmit=async e=>{e.preventDefault();try{await Auth.updateProfile(new FormData(e.target));this.alert('Account updated.');this.renderNav()}catch(x){this.alert(x.message,'err')}}},
async ordersView(){if(!this.state.user)return this.go('login');let {data,error}=await db.from('orders').select('*,order_items(*)').eq('user_id',this.state.user.id).order('created_at',{ascending:false});if(error)return this.alert(error.message,'err');this.view(`<h2>${t('orders')} (${data.length})</h2>${data.map(o=>`<div class="card"><strong>Order #${o.order_number}</strong><div>${new Date(o.created_at).toLocaleString()}</div><div>Status: ${o.status}</div><div>Total: ${Number(o.total_usd).toFixed(2)} USD</div><ul>${(o.order_items||[]).map(i=>`<li>${this.esc(i.product_title)} × ${i.quantity}</li>`).join('')}</ul></div>`).join('')||'<div class="card">You have not placed any orders yet.</div>'}`)},
async footer(){const {data}=await db.from('pages').select('*').eq('enabled',true);document.getElementById('footer-links').innerHTML=(data||[]).map(p=>`<a href="#" class="btn footer-page" data-id="${p.id}">${this.esc(localize(p,'title'))}</a>`).join('');document.querySelectorAll('.footer-page').forEach(a=>a.onclick=e=>{e.preventDefault();let p=(data||[]).find(x=>String(x.id)===a.dataset.id);this.modal(`<h2>${this.esc(localize(p,'title'))}</h2><div>${p.content||''}</div>`)})},
async refreshShell(){await Auth.refresh();this.renderNav();await this.notifications()},
async start(){document.getElementById('year').textContent=new Date().getFullYear();await this.loadSettings();this.applySettings();await Auth.refresh();await Products.load();await this.footer();await this.notifications();this.renderNav();this.route();
 document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{this.state.lang=b.dataset.lang;localStorage.setItem('sf_lang',b.dataset.lang);this.applySettings();this.footer();this.route()});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{this.state.theme=b.dataset.theme;localStorage.setItem('sf_theme',b.dataset.theme);this.applySettings()});document.getElementById('modal-close').onclick=()=>document.getElementById('modal').classList.add('hidden');document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.add('hidden')};document.getElementById('notify-btn').onclick=()=>document.getElementById('notify-panel').classList.toggle('hidden');document.getElementById('notify-close').onclick=()=>document.getElementById('notify-panel').classList.add('hidden');window.addEventListener('hashchange',()=>this.route());db.auth.onAuthStateChange(()=>setTimeout(()=>this.refreshShell(),0));
}};
Store.start().catch(e=>{console.error(e);Store.alert(e.message||String(e),'err')});